export const LOAD_COMMANDS = "LOAD_COMMANDS";
export const LOAD_COMMAND_ITEMS = "LOAD_COMMAND_ITEMS";
export const ADD_COMMAND = "ADD_COMMANDS";
export const DELETE_COMMAND = "DELETE_COMMAND";
export const PAY_COMMAND = "PAY_COMMAND";